Repository the-data-base/nhl-data, pull requests merged in 2022-09, with the labels that each got.

#53 Features/shifts goals
  analyses/archive/goalshifts.sql
  analyses/archive/plays_shifts.sql
  analyses/archive/seconds_between_shifts.sql
  analyses/archive/test_game_state.sql
  dbt_project.yml
  models/analytics/intermediate/d_shifts.sql
  models/analytics/intermediate/d_shifts.yml
  models/analytics/intermediate/f_plays.sql
  models/analytics/intermediate/f_plays.yml
  models/staging/_sources.yml
  models/staging/stg_nhl__live_plays.sql
  models/staging/stg_nhl__live_plays.yml
  models/staging/stg_nhl__shifts.sql
  models/staging/stg_nhl__shifts.yml
  models/staging/stg_nhl__shifts_time.sql
  models/staging/stg_nhl__shifts_time.yml
Labels: enhancement

#56 Feature engineering: Corsi, Fenwick, & other shot features
  models/analytics/core/f_player_season.sql
  models/analytics/core/f_player_season.yml
  models/analytics/intermediate/d_schedule.yml
Labels: enhancement, feature-engineering

#65 Add f_team_season to dbt
  models/analytics/core/f_team_season.sql
  models/analytics/core/f_team_season.yml
Labels: feature-engineering
